import {FaStar} from 'react-icons/fa';

const data = [
    {
        id: '1',
        img1: './images/bag1.jpg',
        img2: './images/bag1.jpg',
        title: 'Beige handbag',
        star: <FaStar className="rating-star" />,
        reviews: '(96 reviews)',
        prevPrice: '2999',
        newPrice: '1599',
        color: 'beige',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '2',
        img1: './images/bag2.jpg',
        img2: './images/bag2.jpg',
        title: 'Green round handbag',
        star: <FaStar className="rating-star" />,
        reviews: '(45 reviews)',
        prevPrice: '2566',
        newPrice: '1099',
        color: 'green',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '3',
        img1: './images/bag3.jpg',
        img2: './images/bag3.jpg',
        title: 'Leather handbag',
        star: <FaStar className="rating-star" />,
        reviews: '(56 reviews)',
        prevPrice: '',
        newPrice: '2190',
        color: 'green',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '4',
        img1: './images/bag4.jpg',
        img2: './images/bag4.jpg',
        title: 'College bag',
        star: <FaStar className="rating-star" />,
        reviews: '(54 reviews)',
        prevPrice: '3499',
        newPrice: '599',
        color: 'brown',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '5',
        img1: './images/bag5.jpg',
        img2: './images/bag5.jpg',
        title: 'Pink handbag',
        star: <FaStar className="rating-star" />,
        reviews: '(21 reviews)',
        prevPrice: '3200',
        newPrice: '1300',
        color: 'pink',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '6',
        img1: './images/bag6.jpg',
        img2: './images/bag6.jpg',
        title: 'Black handbag',
        star: <FaStar className="rating-star" />,
        reviews: '(33 reviews)',
        prevPrice: '5600',
        newPrice: '2999',
        color: 'black',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '7',
        img1: './images/bag7.jpg',
        img2: './images/bag7.jpg',
        title: 'Unicorn Hnadbag',
        star: <FaStar className="rating-star" />,
        reviews: '(88 reviews)',
        prevPrice: '3499',
        newPrice: '1299',
        color: 'pink',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '8',
        img1: './images/bag9.jpg',
        img2: './images/bag9.jpg',
        title: 'White slingbag',
        star: <FaStar className="rating-star" />,
        reviews: '(22 reviews)',
        prevPrice: '3899',
        newPrice: '3200',
        color: 'white',
        company: "Women",
        category: 'handbag',

    },
    {
        id: '9',
        img1: './images/bcropf.jpg',
        img2: './images/bcropb.jpg',
        title: 'Black crop top',
        star: <FaStar className="rating-star" />,
        reviews: '(77 reviews)',
        prevPrice: '4309',
        newPrice: '2399',
        color: 'black',
        company: "Women",
        category: 'croptop',

    },
    {
        id: '10',
        img1: './images/gcrop.jpg',
        img2: './images/gcrop.jpg',
        title: 'Grey crop top',
        star: <FaStar className="rating-star" />,
        reviews: '(12 reviews)',
        prevPrice: '2300',
        newPrice: '1199',
        color: 'grey',
        company: "Women",
        category: 'croptop',

    },
    {
        id: '11',
        img1: './images/bcrop2.jpg',
        img2: './images/lcrop.jpg',
        title: 'Black cute crop top',
        star: <FaStar className="rating-star" />,
        reviews: '(99 reviews)',
        prevPrice: '4999',
        newPrice: '1299',
        color: 'black',
        company: "Women",
        category: 'croptop',

    },
    {
        id: '12',
        img1: './images/gsweater.jpg',
        img2: './images/osweater.jpg',
        title: 'Green crop sweater',
        star: <FaStar className="rating-star" />,
        reviews: '(33 reviews)',
        prevPrice: '',
        newPrice: '999',
        color: 'green',
        company: "Women",
        category: 'croptop',

    },
    {
        id: '13',
        img1: './images/wcrop1.jpg',
        img2: './images/wcrop2.jpg',
        title: 'White Crop top',
        star: <FaStar className="rating-star" />,
        reviews: '(21 reviews)',
        prevPrice: '1299',
        newPrice: '999',
        color: 'white',
        company: "Women",
        category: 'croptop',

    },
    {
        id: '14',
        img1: './images/bhoodie.jpg',
        img2: 'bhoodie2.jpg',
        title: 'Black Sweatshirt',
        star: <FaStar className="rating-star" />,
        reviews: '(11 reviews)',
        prevPrice: '3199',
        newPrice: '2199',
        color: 'black',
        company: "Women",
        category: 'sweatshirt',

    },
    {
        id: '15',
        img1: './images/brhoodie.jpg',
        img2: './images/brhoodie.jpg',
        title: 'Brown Sweatshirt',
        star: <FaStar className="rating-star" />,
        reviews: '(21 reviews)',
        prevPrice: '4199',
        newPrice: '2399',
        color: 'brown',
        company: "Women",
        category: 'sweatshirt',

    },
    {
        id: '16',
        img1: './images/blhoodie.jpg',
        img2: './images/ghoodie.jpg',
        title: 'Stylish sweatshirt',
        star: <FaStar className="rating-star" />,
        reviews: '(23 reviews)',
        prevPrice: '',
        newPrice: '1299',
        color: 'blue',
        company: "Women",
        category: 'sweatshirt',

    },
    {
        id: '17',
        img1: './images/foxg2.jpg',
        img2: './images/foxg.jpg',
        title: "Men's sweatshirt",
        star: <FaStar className="rating-star" />,
        reviews: '(32 reviews)',
        prevPrice: '4399',
        newPrice: '3499',
        color: 'white',
        company: "Men",
        category: 'sweatshirt',

    },
    {
        id: '18',
        img1: './images/tshirtc.jpg',
        img2: './images/tshirtc2.jpg',
        title: 'Beige Sweatshirt',
        star: <FaStar className="rating-star" />,
        reviews: '(11 reviews)',
        prevPrice: '2399',
        newPrice: '1099',
        color: 'beige',
        company: "Men",
        category: 'sweatshirt',

    },
    {
        id: '19',
        img1: './images/whoodie2.jpg',
        img2: './images/whoodie.jpg',
        title: 'White Women Sweatshirt',
        star: <FaStar className="rating-star" />,
        reviews: '(23 reviews)',
        prevPrice: '1999',
        newPrice: '899',
        color: 'white',
        company: "Women",
        category: 'sweatshirt',

    },
    {
        id: '20',
        img1: './images/skirt1.jpg',
        img2: './images/skirt2.jpg',
        title: 'Black skirt',
        star: <FaStar className="rating-star" />,
        reviews: '(9 reviews)',
        prevPrice: '1799',
        newPrice: '999',
        color: 'black',
        company: "Women",
        category: 'pants',

    },
    {
        id: '21',
        img1: './images/scarf2.jpg',
        img2: './images/scarf1.jpg',
        title: 'Woollen scarf',
        star: <FaStar className="rating-star" />,
        reviews: '(10 reviews)',
        prevPrice: '3999',
        newPrice: '2500',
        color: 'green',
        company: "Women",
        category: 'accessories',

    },
    {
        id: '22',
        img1: './images/clip.jpg',
        img2: './images/clip.jpg',
        title: 'Hair clips',
        star: <FaStar className="rating-star" />,
        reviews: '(55 reviews)',
        prevPrice: '4399',
        newPrice: '1999',
        color: 'brown',
        company: "Women",
        category: 'accessories',

    },
    {
        id: '23',
        img1: './images/beanie.jpg',
        img2: './images/',
        title: 'Beanie',
        star: <FaStar className="rating-star" />,
        reviews: '(22 reviews)',
        prevPrice: '999',
        newPrice: '499',
        color: 'white',
        company: "Women",
        category: 'accessories',

    },
    {
        id: '24',
        img1: './images/cap1.jpg',
        img2: './images/cap2.jpg',
        title: 'White hat',
        star: <FaStar className="rating-star" />,
        reviews: '( reviews)',
        prevPrice: '2999',
        newPrice: '999',
        color: 'white',
        company: "Men",
        category: 'accessories',

    },
    {
        id: '25',
        img1: './images/mtshirt.jpg',
        img2: './images/mtshirt2.jpg',
        title: 'Maroon Tshirt',
        star: <FaStar className="rating-star" />,
        reviews: '( reviews)',
        prevPrice: '3399',
        newPrice: '2499',
        color: 'brown',
        company: "Men",
        category: 'tshirt',

    },
    {
        id: '26',
        img1: './images/foxw.jpg',
        img2: './images/foxw2.jpg',
        title: 'White fox Tshirt',
        star: <FaStar className="rating-star" />,
        reviews: '(29 reviews)',
        prevPrice: '1299',
        newPrice: '2499',
        color: 'white',
        company: "Men",
        category: 'tshirt',

    },
    {
        id: '27',
        img1: './images/tshirtb.jpg',
        img2: './images/tshirtb.jpg',
        title: 'Black Basic Tshirt',
        star: <FaStar className="rating-star" />,
        reviews: '(77 reviews)',
        prevPrice: '3499',
        newPrice: '1499',
        color: 'black',
        company: "Men",
        category: 'tshirt',

    },
    {
        id: '28',
        img1: './images/yshoe.jpg',
        img2: './images/yshoe.jpg',
        title: 'Yellow shoes',
        star: <FaStar className="rating-star" />,
        reviews: '(9 reviews)',
        prevPrice: '1799',
        newPrice: '499',
        color: 'yellow',
        company: "Women",
        category: 'shoes',

    },
    {
        id: '29',
        img1: './images/wshoe6.jpg',
        img2: './images/wshoe6.jpg',
        title: 'Black & white shoes',
        star: <FaStar className="rating-star" />,
        reviews: '(12 reviews)',
        prevPrice: '1099',
        newPrice: '1999',
        color: 'white',
        company: "Women",
        category: 'shoes',

    },
    {
        id: '30',
        img1: './images/blueshoe.jpg',
        img2: './images/blueshoe.jpg',
        title: 'Blue shoes',
        star: <FaStar className="rating-star" />,
        reviews: '(22 reviews)',
        prevPrice: '2299',
        newPrice: '1499',
        color: 'blue',
        company: "Women",
        category: 'shoes',

    },
    {
        id: '31',
        img1: './images/flip1.jpg',
        img2: './images/flip2.jpg',
        title: 'Flip flops',
        star: <FaStar className="rating-star" />,
        reviews: '(44 reviews)',
        prevPrice: '2399',
        newPrice: '999',
        color: 'green',
        company: "Women",
        category: 'shoes',

    },
    {
        id: '32',
        img1: './images/boot1.jpg',
        img2: './images/boot2.jpg',
        title: 'White boots',
        star: <FaStar className="rating-star" />,
        reviews: '(99 reviews)',
        prevPrice: '5799',
        newPrice: '2500',
        color: 'white',
        company: "Women",
        category: 'shoes',

    },
    {
        id: '33',
        img1: './images/bshoe6.jpg',
        img2: './images/bshoe6.jpg',
        title: 'Classy shoes',
        star: <FaStar className="rating-star" />,
        reviews: '(98 reviews)',
        prevPrice: '4999',
        newPrice: '2499',
        color: 'black',
        company: "Women",
        category: 'shoes',

    },
    {
        id: '34',
        img1: './images/bshoe3.jpg',
        img2: './images/bshoe3.jpg',
        title: 'Black shoes',
        star: <FaStar className="rating-star" />,
        reviews: '(23 reviews)',
        prevPrice: '3299',
        newPrice: '1499',
        color: 'black',
        company: "Women",
        category: 'shoes',

    },
    {
        id: '35',
        img1: './images/jeans.jpg',
        img2: './images/jeansb.jpg',
        title: 'Jeans',
        star: <FaStar className="rating-star" />,
        reviews: '(33 reviews)',
        prevPrice: '3199',
        newPrice: '1999',
        color: 'blue',
        company: "Men",
        category: 'pants',

    },
    {
        id: '36',
        img1: './images/shorts.jpg',
        img2: './images/shorts.jpg',
        title: 'Denim shorts',
        star: <FaStar className="rating-star"/>,
        reviews: '(13 reviews)',
        prevPrice: '1399',
        newPrice: '499',
        color: 'blue',
        company: "Women",
        category: 'pants',

    }    
]

export default data;